# Generated by Django 5.2.6 on 2025-09-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(blank=True, choices=[('Life', 'Жизнь'), ('Health', 'Здоровье'), ('Beauty', 'Красота'), ('Entertainment', 'Развлечения'), ('Style', 'Стиль')], max_length=255, null=True),
        ),
    ]
