# Generated by Django 5.2.6 on 2025-09-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_alter_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(blank=True, choices=[('Life', 'Жизнь'), ('Health', 'Health'), ('Beauty', 'Beauty'), ('Entertainment', 'Entertainment'), ('Style', 'Style')], max_length=255, null=True),
        ),
    ]
