# Generated by Django 5.2.6 on 2025-09-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_alter_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(blank=True, choices=[('Жизнь', 'Жизнь'), ('Здоровье', 'Здоровье'), ('Красота', 'Красота'), ('Развлечения', 'Развлечения'), ('Стиль', 'Стиль')], max_length=255, null=True),
        ),
    ]
